---

- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apache2

- name: Create directories for username
  sudo: yes
  sudo_user: "{{ username }}"
  file: path={{ item }} state=directory owner={{username}} group={{username}}
  with_items:
    - /home/{{username}}/bin
    - /home/{{username}}/workspaces

            
